export const variables = {
	APPCHECK_DEBUG_TOKEN: import.meta.env.VITE_APPCHECK_DEBUG_TOKEN,
	RECAPTCHA_V3_PROVIDER: import.meta.env.VITE_RECAPTCHA_V3_PROVIDER,
	FACEBOOK_DOMAIN_VERIFICATION: import.meta.env.VITE_FACEBOOK_DOMAIN_VERIFICATION,
	FIRE_API_KEY: import.meta.env.VITE_FIRE_API_KEY,
	FIRE_AUTH_DOMAIN: import.meta.env.VITE_FIRE_AUTH_DOMAIN,
	FIRE_PROJECT_ID: import.meta.env.VITE_FIRE_PROJECT_ID,
	FIRE_STORAGE_BUCKET: import.meta.env.VITE_FIRE_STORAGE_BUCKET,
	FIRE_MESSAGING_SENDER_ID: import.meta.env.VITE_FIRE_MESSAGING_SENDER_ID,
	FIRE_APP_ID: import.meta.env.VITE_FIRE_APP_ID,
	FIRE_MEASUREMENT_ID: import.meta.env.VITE_FIRE_MEASUREMENT_ID,
	FIRE_USE_EMULATORS: import.meta.env.VITE_FIRE_USE_EMULATORS
};
